### ISSUE TITLE
Change regexp

### ISSUE THREAD

**Issue by rbark** [stofolus/pnr-scanner#21]
```javascript
class Pnr {
  static get regex() {
    return /\b(19|20)?[0-9]{2}((0[0-9])|(10|11|12))(([0-2][0-9])|(3[0-1])|(([7-8][0-9])|(6[1-9])|(9[0-1])))[- \+]*[0-9]{4}/g;
  }
```
Change the last piece  ` [- \+]*[0-9] to [- \+]?[0-9]`
besides that, I think a much simpler regex would be more readable and the number are still validated after it pass the regexp. But thats just a personal  opinion.

**Comment by stofolus** [comment]
@rbark feel free to submit a PR
