### ISSUE TITLE
Exclude/whitelist false positives

### ISSUE THREAD

**Issue by cederstrom** [stofolus/pnr-scanner#31]
**Scenario**
pnr-scanner finds something which looks like a pnr but it is not a pnr

Ex.:
`"phoneNummer": "0701234567"`

**Suggestion**
Some kind of whitelist/ignore/disable functionality to skip scanning a file, section or line.

@stofolus @hansson, thoughts?

**Comment by hansson** [comment]
Sounds like a very important feature for a not so very unlikely scenario....I'll look into building a whitelist!

**Comment by stofolus** [comment]
Fixed
