### ISSUE TITLE
Collision after fix

### ISSUE THREAD

**Issue by phlogios** [stofolus/pnr-scanner#40]
Given 2 sensitive similar-in-time PNRs that are intentionally different for testing purposes, the fix command merges them to the same PNR.

I suggest an alternative, optional fix method that uses the sensitive PNR as a seed in a random lookup in the same year. This helps in cases where only uniqueness is important.

**Comment by stofolus** [comment]
Could you give an example?

**Comment by phlogios** [comment]
Let's say you have a test that requires 2 valid PNRs.
PNR A can access resource X,
PNR B cannot access resource X.
A and B are both valid (unsafe) PNRs, with very similar dates.

pnr-scanner -f will try to find the closest safe PNRs to replace A and B with, and can accidentally pick the same safe PNR for both, which breaks the test.

**Comment by stofolus** [comment]
Ahh. That's not the intended behavior. It should never resolve two different numbers to the same mocked number. I'll look into it at the end of this week

**Comment by stofolus** [comment]
This hasn't been fixed yet. The commits were tagged wrong
