### ISSUE TITLE
False positives pnr is reported in v0.4.0

### ISSUE THREAD

**Issue by OlofFredriksson** [stofolus/pnr-scanner#41]
Latest version (0.4.0) reports safe pnr as unsafe

# How to reproduce
Create **index.js** containing a pnr, existing in the mock-files (https://github.com/stofolus/pnr-scanner/blob/master/mocks/Testpersonnummer_170117.csv#L2)
`201701012393`

Using latest version of pnr-scanner

> $ npx pnr-scanner@0.4.0 index.js
>
> npx: installed 20 in 3.852s
> pnr-scan: 2.646ms
> C:\PATH\index.js
>     201701012393 on line 1
> 

Using 0.3.2

> $ npx pnr-scanner@0.3.2 index.js
>
> npx: installed 20 in 3.902s
> pnr-scan: 2.505ms
>

**Comment by hansson** [comment]
https://github.com/stofolus/pnr-scanner/blob/master/lib/finder.js#L27 is probably the problem. 

should be changed to: ` const validator = new Validator([...FileMockDataReader.fetch(), ...WhitelistReader.fetch(searchPath)]);`

**Comment by stofolus** [comment]
This has been fixed
