### ISSUE TITLE
false positives?

### ISSUE THREAD

**Issue by 00Zeb** [stofolus/pnr-scanner#44]
These are detected as PNR's:

String telephone = "+460311234567";
private static final long serialVersionUID = 1905197073153504885L;

Also the serialVersionUID cannot be whitelisted.

**Comment by rbark** [comment]
Jag har en fix för denna, jag lägger en pr ikväll,

**Comment by stofolus** [comment]
Possibly fixed by @rbark. I will release a new version soon that should include the fix
