### ISSUE TITLE
Support for excluding files during scan

### ISSUE THREAD

**Issue by rbark** [stofolus/pnr-scanner#48]
I we have datafiles in our repo that we know only consists of data that isnt pnr's, we want toi exclude that file during scan,  we have that problem right now, when we take out statistics and we get a lot of numbers that matches pnr's, but it is only amounts of money or other statistics.

**Comment by stofolus** [comment]
Have you tried using a custom glob pattern? I'm not great with globs but maybe something like 

```
❯ npx pnr-scanner . -p "!(node_modules){,/**/!(offending_filename.csv)*}"
```

**Comment by rbark** [comment]
We have automated builds and don't want to change the way it is run, there is support for numbers in a whitelist-file, maybe that file also could contain files to be excluded.

**Comment by stofolus** [comment]
Sure, it could be changed into a config file where you can override the pattern, add a whitelist of numbers and a list of files to ignore.

Feel free to submit a PR 😄
