### ISSUE TITLE
Separate loading of mock data from validation

### ISSUE THREAD

**Issue by cederstrom** [stofolus/pnr-scanner#8]
As is, loading of mock data and validation is entangled. In order to support loading mock data from other sources (e.g. APIs) we should separate these two concerns.

In practice this means that we need to create an instance of `Validator` and pass either pre-loaded data, or pass a data loader instance (like you suggested on Hangouts earlier) to it. Any solution should do.

@stofolus, thoughts?

**Comment by stofolus** [comment]
Doesn't really matter. I vote for whatever solution is the simplest. I'm guessing passing data would be the easiest. I'm guessing you meant something like this? Would probably be easier than passing a factory. And more isolated & test friendly
```javascript
class Validator {
  constructor(mockList) {
    this.mockList = mockList;
  }
  isMock(pnr) {
    return mockList.includes(Pnr.normalizePnr(pnr));
  }
}
```

**Comment by cederstrom** [comment]
Pretty much :)

I'll whip up a PR!
